# makefile for fit_raw
#
#
include $(MAKECFG).$(SYSTEM)



INCLUDE= -I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn/fit -I$(IPATH)/superdarn
SRC = fit_raw.c fit_acf.c fit_acf.h
OBJS = fit_raw.o
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT=fit_raw
LINK="1"



include $(MAKELIB).$(SYSTEM)
